[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "false"

[context.production]
  command = "npm run build"

[context.preview]
  command = "npm run build"
  publish = "dist"
  base = "/"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true

[functions.dev]
  command = "npm run dev"
  devCommand = "npm run dev"

[context.preview.environment]
  NODE_VERSION = "18"
  BRANCH = "preview" 